/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-01-16 20:54:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.JSPFiles.include.assets;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class js_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/F:/Desktop/Ensias_S3/Projet%20S3/Realisation/eclipse_workSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/e-colocation/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1579207852914L));
    _jspx_dependants.put("/WEB-INF/taglibs.jsp", Long.valueOf(1579207865112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!--   Core JS Files   -->\r\n");
      out.write("  <script src=\"presentation/assets/js/core/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"presentation/assets/js/core/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"presentation/assets/js/core/bootstrap-material-design.min.js\"></script>\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/perfect-scrollbar.jquery.min.js\"></script>\r\n");
      out.write("  <!-- Plugin for the momentJs  -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/moment.min.js\"></script>\r\n");
      out.write("  <!--  Plugin for Sweet Alert -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/sweetalert2.js\"></script>\r\n");
      out.write("  <!-- Forms Validations Plugin -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/jquery.validate.min.js\"></script>\r\n");
      out.write("  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/jquery.bootstrap-wizard.js\"></script>\r\n");
      out.write("  <!--\tPlugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/bootstrap-selectpicker.js\"></script>\r\n");
      out.write("  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/jquery.dataTables.min.js\"></script>\r\n");
      out.write("  <!--\tPlugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/bootstrap-tagsinput.js\"></script>\r\n");
      out.write("  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/jasny-bootstrap.min.js\"></script>\r\n");
      out.write("  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/fullcalendar.min.js\"></script>\r\n");
      out.write("  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/jquery-jvectormap.js\"></script>\r\n");
      out.write("  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/nouislider.min.js\"></script>\r\n");
      out.write("  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js\"></script>\r\n");
      out.write("  <!-- Library for adding dinamically elements -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/arrive.min.js\"></script>\r\n");
      out.write("  <!-- Chartist JS -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/chartist.min.js\"></script>\r\n");
      out.write("  <!--  Notifications Plugin    -->\r\n");
      out.write("  <script src=\"presentation/assets/js/plugins/bootstrap-notify.js\"></script>\r\n");
      out.write("  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("  <script src=\"presentation/assets/js/material-dashboard.js?v=2.1.1\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      $().ready(function() {\r\n");
      out.write("        $sidebar = $('.sidebar');\r\n");
      out.write("\r\n");
      out.write("        $sidebar_img_container = $sidebar.find('.sidebar-background');\r\n");
      out.write("\r\n");
      out.write("        $full_page = $('.full-page');\r\n");
      out.write("\r\n");
      out.write("        $sidebar_responsive = $('body > .navbar-collapse');\r\n");
      out.write("\r\n");
      out.write("        window_width = $(window).width();\r\n");
      out.write("\r\n");
      out.write("        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();\r\n");
      out.write("\r\n");
      out.write("        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {\r\n");
      out.write("          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {\r\n");
      out.write("            $('.fixed-plugin .dropdown').addClass('open');\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $('.fixed-plugin a').click(function(event) {\r\n");
      out.write("          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active\r\n");
      out.write("          if ($(this).hasClass('switch-trigger')) {\r\n");
      out.write("            if (event.stopPropagation) {\r\n");
      out.write("              event.stopPropagation();\r\n");
      out.write("            } else if (window.event) {\r\n");
      out.write("              window.event.cancelBubble = true;\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.fixed-plugin .active-color span').click(function() {\r\n");
      out.write("          $full_page_background = $('.full-page-background');\r\n");
      out.write("\r\n");
      out.write("          $(this).siblings().removeClass('active');\r\n");
      out.write("          $(this).addClass('active');\r\n");
      out.write("\r\n");
      out.write("          var new_color = $(this).data('color');\r\n");
      out.write("\r\n");
      out.write("          if ($sidebar.length != 0) {\r\n");
      out.write("            $sidebar.attr('data-color', new_color);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($full_page.length != 0) {\r\n");
      out.write("            $full_page.attr('filter-color', new_color);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($sidebar_responsive.length != 0) {\r\n");
      out.write("            $sidebar_responsive.attr('data-color', new_color);\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.fixed-plugin .background-color .badge').click(function() {\r\n");
      out.write("          $(this).siblings().removeClass('active');\r\n");
      out.write("          $(this).addClass('active');\r\n");
      out.write("\r\n");
      out.write("          var new_color = $(this).data('background-color');\r\n");
      out.write("\r\n");
      out.write("          if ($sidebar.length != 0) {\r\n");
      out.write("            $sidebar.attr('data-background-color', new_color);\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.fixed-plugin .img-holder').click(function() {\r\n");
      out.write("          $full_page_background = $('.full-page-background');\r\n");
      out.write("\r\n");
      out.write("          $(this).parent('li').siblings().removeClass('active');\r\n");
      out.write("          $(this).parent('li').addClass('active');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          var new_image = $(this).find(\"img\").attr('src');\r\n");
      out.write("\r\n");
      out.write("          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {\r\n");
      out.write("            $sidebar_img_container.fadeOut('fast', function() {\r\n");
      out.write("              $sidebar_img_container.css('background-image', 'url(\"' + new_image + '\")');\r\n");
      out.write("              $sidebar_img_container.fadeIn('fast');\r\n");
      out.write("            });\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {\r\n");
      out.write("            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');\r\n");
      out.write("\r\n");
      out.write("            $full_page_background.fadeOut('fast', function() {\r\n");
      out.write("              $full_page_background.css('background-image', 'url(\"' + new_image_full_page + '\")');\r\n");
      out.write("              $full_page_background.fadeIn('fast');\r\n");
      out.write("            });\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($('.switch-sidebar-image input:checked').length == 0) {\r\n");
      out.write("            var new_image = $('.fixed-plugin li.active .img-holder').find(\"img\").attr('src');\r\n");
      out.write("            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');\r\n");
      out.write("\r\n");
      out.write("            $sidebar_img_container.css('background-image', 'url(\"' + new_image + '\")');\r\n");
      out.write("            $full_page_background.css('background-image', 'url(\"' + new_image_full_page + '\")');\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($sidebar_responsive.length != 0) {\r\n");
      out.write("            $sidebar_responsive.css('background-image', 'url(\"' + new_image + '\")');\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.switch-sidebar-image input').change(function() {\r\n");
      out.write("          $full_page_background = $('.full-page-background');\r\n");
      out.write("\r\n");
      out.write("          $input = $(this);\r\n");
      out.write("\r\n");
      out.write("          if ($input.is(':checked')) {\r\n");
      out.write("            if ($sidebar_img_container.length != 0) {\r\n");
      out.write("              $sidebar_img_container.fadeIn('fast');\r\n");
      out.write("              $sidebar.attr('data-image', '#');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if ($full_page_background.length != 0) {\r\n");
      out.write("              $full_page_background.fadeIn('fast');\r\n");
      out.write("              $full_page.attr('data-image', '#');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            background_image = true;\r\n");
      out.write("          } else {\r\n");
      out.write("            if ($sidebar_img_container.length != 0) {\r\n");
      out.write("              $sidebar.removeAttr('data-image');\r\n");
      out.write("              $sidebar_img_container.fadeOut('fast');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if ($full_page_background.length != 0) {\r\n");
      out.write("              $full_page.removeAttr('data-image', '#');\r\n");
      out.write("              $full_page_background.fadeOut('fast');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            background_image = false;\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.switch-sidebar-mini input').change(function() {\r\n");
      out.write("          $body = $('body');\r\n");
      out.write("\r\n");
      out.write("          $input = $(this);\r\n");
      out.write("\r\n");
      out.write("          if (md.misc.sidebar_mini_active == true) {\r\n");
      out.write("            $('body').removeClass('sidebar-mini');\r\n");
      out.write("            md.misc.sidebar_mini_active = false;\r\n");
      out.write("\r\n");
      out.write("            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();\r\n");
      out.write("\r\n");
      out.write("          } else {\r\n");
      out.write("\r\n");
      out.write("            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');\r\n");
      out.write("\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("              $('body').addClass('sidebar-mini');\r\n");
      out.write("\r\n");
      out.write("              md.misc.sidebar_mini_active = true;\r\n");
      out.write("            }, 300);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          // we simulate the window Resize so the charts will get updated in realtime.\r\n");
      out.write("          var simulateWindowResize = setInterval(function() {\r\n");
      out.write("            window.dispatchEvent(new Event('resize'));\r\n");
      out.write("          }, 180);\r\n");
      out.write("\r\n");
      out.write("          // we stop the simulation of Window Resize after the animations are completed\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            clearInterval(simulateWindowResize);\r\n");
      out.write("          }, 1000);\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      // Javascript method's body can be found in assets/js/demos.js\r\n");
      out.write("      md.initDashboardPageCharts();\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("  </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
