/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-02-04 21:12:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.JSPFiles.Offreur;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1579207852914L));
    _jspx_dependants.put("jar:file:/C:/eclipse_workSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/e-colocation/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("/WEB-INF/taglibs.jsp", Long.valueOf(1579207865112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <!--#########################  Head inclusion  ###################################-->\r\n");
      out.write("\t\r\n");
      out.write("        \t\t\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\r\n");
      out.write("    <!--##############################################################################-->\r\n");
      out.write("  <title>\r\n");
      out.write("    Material Dashboard by Creative Tim\r\n");
      out.write("  </title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("  <div class=\"wrapper \">\r\n");
      out.write("  <!--#########################  Sidebar inclusion  ###################################-->\r\n");
      out.write("\t\r\n");
      out.write("        \t\t\t\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\r\n");
      out.write("    <!--##############################################################################-->\r\n");
      out.write("    <div class=\"main-panel\">\r\n");
      out.write("     <!--#########################  Navbar inclusion  ###################################-->\r\n");
      out.write("\t\r\n");
      out.write("        \t\t\t\t");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\r\n");
      out.write("    <!--##############################################################################-->\r\n");
      out.write("      <div class=\"content\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header card-header-primary\">\r\n");
      out.write("                  <h4 class=\"card-title\">Editer votre Profil</h4>\r\n");
      out.write("                  <p class=\"card-category\">Completez votre profil</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                <div id=\"profilSuccess\">\r\n");
      out.write("                 </div>\r\n");
      out.write("                  <div id=\"profil\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"\">Nom</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"nom\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nom}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"\">Prenom</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"prenom\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.prenom}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"\">Mot de passe</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"mdp\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"\">Ville</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"ville\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.ville}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"\">Adresse</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"adresse\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.adresse}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label>Vous etes</label>\r\n");
      out.write("                          <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"\"> Metez une petites description sur vous.</label>\r\n");
      out.write("                            <textarea class=\"form-control\" rows=\"5\" id=\"description\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-primary pull-right\" onClick=\"modifierProfil()\">Enregistrez</button>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("              <div class=\"card card-profile\">\r\n");
      out.write("                <div class=\"card-avatar\">\r\n");
      out.write("                  <a href=\"#pablo\">\r\n");
      out.write("                    <img class=\"img\" src=\"presentation/assets/img/faces/said.jpg\" />\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h6 class=\"card-category text-gray\">Employe</h6>\r\n");
      out.write("                  <h4 class=\"card-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nom}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.prenom}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                  <p class=\"card-description\">\r\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header card-header-primary\">\r\n");
      out.write("                  <h4 class=\"card-title\">Editer votre exigences</h4>\r\n");
      out.write("                  <p class=\"card-category\">Completez votre profil</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <form id=\"caracteristiques\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"bmd-label-floating\">Age</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"age\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"bmd-label-floating\">Activite principale</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"activite\" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"bmd-label-floating\">Religion</label>\r\n");
      out.write("                          <input type=\"email\" class=\"form-control\" id=\"religion\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"bmd-label-floating\">Fumeur</label>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                                <label class=\"form-check-label\">Oui\r\n");
      out.write("                                  <input class=\"form-check-input\" type=\"radio\" value=\"\" name=\"fumeur\">\r\n");
      out.write("                                  <span class=\"form-check-sign\">\r\n");
      out.write("                                    <span class=\"check\"></span>\r\n");
      out.write("                                  </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <label class=\"form-check-label\">Non\r\n");
      out.write("                                  <input class=\"form-check-input\" type=\"radio\" value=\"\" name=\"fumeur\">\r\n");
      out.write("                                  <span class=\"form-check-sign\">\r\n");
      out.write("                                    <span class=\"check\"></span>\r\n");
      out.write("                                  </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                              </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"bmd-label-floating\">Vous aimez les animaux domestiques</label>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                                <label class=\"form-check-label\">Oui\r\n");
      out.write("                                  <input class=\"form-check-input\" type=\"radio\" value=\"\" name=\"animaux\">\r\n");
      out.write("                                  <span class=\"form-check-sign\">\r\n");
      out.write("                                    <span class=\"check\"></span>\r\n");
      out.write("                                  </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <label class=\"form-check-label\">Non\r\n");
      out.write("                                  <input class=\"form-check-input\" type=\"radio\" value=\"\" name=\"animaux\">\r\n");
      out.write("                                  <span class=\"form-check-sign\">\r\n");
      out.write("                                    <span class=\"check\"></span>\r\n");
      out.write("                                  </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                              </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"bmd-label-floating\">Experience de colocation</label>\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <label class=\"form-check-label\">Oui\r\n");
      out.write("                                  <input class=\"form-check-input\" type=\"radio\" value=\"\" name=\"exp_colo\">\r\n");
      out.write("                                  <span class=\"form-check-sign\">\r\n");
      out.write("                                    <span class=\"check\"></span>\r\n");
      out.write("                                  </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <label class=\"form-check-label\">Non\r\n");
      out.write("                                  <input class=\"form-check-input\" type=\"radio\" value=\"\" name=\"exp_colo\">\r\n");
      out.write("                                  <span class=\"form-check-sign\">\r\n");
      out.write("                                    <span class=\"check\"></span>\r\n");
      out.write("                                  </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                              </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label class=\"bmd-label-floating\">Niveau de proprete note sur 10</label>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"proprete\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary pull-right\" onClick=\"modifierExigence()\">Enregistrez</button>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("        <!--#########################  footer inclusion  ###################################-->\r\n");
      out.write("\t\r\n");
      out.write("        \t\t\t\t");
      if (_jspx_meth_c_005fimport_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\r\n");
      out.write("    <!--##############################################################################-->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--#########################  Plugin inclusion  ###################################-->\r\n");
      out.write("\t\r\n");
      out.write("        \t\t\t\t");
      if (_jspx_meth_c_005fimport_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\r\n");
      out.write("    <!--##############################################################################-->\r\n");
      out.write("    \r\n");
      out.write("    <!--#########################  JS lib inclusion  ###################################-->\r\n");
      out.write("\t\r\n");
      out.write("        \t\t\t\t");
      if (_jspx_meth_c_005fimport_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\r\n");
      out.write("    <!--##############################################################################-->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tfunction modifierProfil(){\r\n");
      out.write("\t\tvar form=\"modifierProfil\";\r\n");
      out.write("\t\tvar mdp = $(\"#mdp\").val();\r\n");
      out.write("\t\tvar ville = $(\"#ville\").val();\r\n");
      out.write("\t\tvar adresse = $(\"#adresse\").val();\r\n");
      out.write("\t\tvar description = $(\"#description\").val();\r\n");
      out.write("\t\t$.post(\"O_Profil\",{\r\n");
      out.write("\t\t\tform: form,\r\n");
      out.write("\t\t\tmdp: mdp,\r\n");
      out.write("\t\t\tville: ville,\r\n");
      out.write("\t\t\tadresse: adresse,\r\n");
      out.write("\t\t\tdescription: description\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},function(data, status) {\r\n");
      out.write("\t\t\t$(\"#profilSuccess\").html('<div class=\"alert alert-success\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">'+\r\n");
      out.write("\t\t\t'<i class=\"material-icons\">close</i></button><span><b> Success - </b> This is a regular notification made with \".alert-success\"</span></div>');\r\n");
      out.write("\t\t\tlocation.reload();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/JSPFiles/Offreur/profil.jsp(1,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.proprietaire}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t");
          if (true) {
            _jspx_page_context.forward("../Accueil/accueil.jsp");
            return true;
          }
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/JSPFiles/Offreur/profil.jsp(10,12) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../include/assets/head.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/JSPFiles/Offreur/profil.jsp(22,12) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../include/assets/sidebarOffreur.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/JSPFiles/Offreur/profil.jsp(28,12) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("../include/assets/navbar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f3 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f3_reused = false;
    try {
      _jspx_th_c_005fimport_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f3.setParent(null);
      // /WEB-INF/JSPFiles/Offreur/profil.jsp(228,12) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f3.setUrl("../include/assets/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f3 = _jspx_th_c_005fimport_005f3.doStartTag();
        if (_jspx_th_c_005fimport_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f3);
      _jspx_th_c_005fimport_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f4 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f4_reused = false;
    try {
      _jspx_th_c_005fimport_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f4.setParent(null);
      // /WEB-INF/JSPFiles/Offreur/profil.jsp(235,12) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f4.setUrl("../include/assets/plugin.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f4 = _jspx_th_c_005fimport_005f4.doStartTag();
        if (_jspx_th_c_005fimport_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f4);
      _jspx_th_c_005fimport_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f5 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f5_reused = false;
    try {
      _jspx_th_c_005fimport_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f5.setParent(null);
      // /WEB-INF/JSPFiles/Offreur/profil.jsp(241,12) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f5.setUrl("../include/assets/js.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f5 = _jspx_th_c_005fimport_005f5.doStartTag();
        if (_jspx_th_c_005fimport_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f5);
      _jspx_th_c_005fimport_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f5_reused);
    }
    return false;
  }
}
